simulation:
  replicates: 1
  time_ns: 0.1
  recording_interval_ps: 0.1            
  number_frames: 2
  seed: 2025

  equilibration:
    NVT_heating:  1 # 5000 # 10 ps for each T
    NPT_equilibration: 1 # 50000 # 100 ps for 2 steps
    NPT_unrestrained:  1 #100000 # 200 ps

  # Forcefield settings
  forcefield:
    protein: amber19-all.xml         # options: amber14-all.xml, amber19-all.xml
    water:   amber19/tip4pew.xml     # options: amber14/tip3p.xml, amber19/tip3pfb.xml
    watermodel: tip4pew

  system:
    salt_molar: 0.15              # M for Na+ and Cl-
    temperature_K: 310         # Kelvin
    pressure_atm: 1              # atm
    barostat_interval_steps: 25     # integration steps

  constraints:
    dt_fs: 2
    bonds: HBonds        # options: None, HBonds, AllBonds
    rigid_water: True     # options: True, False
    cutoff_nm: 1.0          # in nm
    ewald_error_tolerance: 0.0005   # PME tolerance
    constraint_tolerance: 0.0001 # 1e-5 high accuarcy for energy 1e-4: recommanded for amber
    friction_ps: 1.0

  metadynamics: 
        enabled: False
        CV:
          COM
        params:
          SIGMA: 0.2    # 0.1-0.5 nm. The width of each Gaussian hill deposited in the free-energy landscape.
          HEIGHT: 0.03  # 0.1–1.0 kJ/mol. The amplitude (energy) of each Gaussian hill
          PACE: 1000     # 100-2000. Frequency of applying hill
          STRIDE: 50    # How often values of your collective variables are written to the COLVAR file.



