mutations:
      - WT
      - R65E

mode: PPi         # options: PPi, molecule, protein

complexes:
  C1s_Gigastasin:
    receptor: C1s
    ligand: Gigastasin
    pdb: pdb/13_C1s-BD001.pdb

  MASP2_Gigastasin:
    receptor: MASP2
    ligand: Gigastasin
    pdb: pdb/13_C1s-BD001.pdb
