[project]
name = "squeezemd"
version = "1.7.9"
description = "SqueezeMD is a autmated Molecular dynamics workflow with extensive post-analysis for PPi"
readme = "README.rst"
authors = [
  {name = "Rüthemann Peter", email = "peter.ruethemann@gmail.com"}
]
maintainers = [
  {name = "peter", email = "peter.ruethemann@gmail.com"}
]
classifiers = [
    # TODO
]
license = {text = "MIT"}
dependencies = [
  "typer"
]
requires-python = ">= 3.12"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project.optional-dependencies]
test = [
    "coverage",  # testing
    "pytest",  # testing
    "ruff",  # linting
    "ty", # checking types
    "ipdb", # debugging
]

[project.urls]
bugs = "https://github.com/pruethemann/squeezemd"
changelog = "https://github.com/pruethemann/squeezemd/blob/master/changelog.md"
homepage = "https://github.com/pruethemann/squeezemd"

[project.scripts]
squeezemd = "squeezemd.cli:app"

# preprocessing
mutate = "squeezemd.preprocessing.mutate_structure:main"

#md
center-traj = "squeezemd.md.center_trajectory:main"
run-md = "squeezemd.md.run_md:main"

# Analysis - Posco
compute-posco-contacts = "squeezemd.analysis.contact_posco.compute_posco_interactions:main"
plot-contact-barplot = "squeezemd.analysis.contact_posco.plot_contact_barplot:main"
plot-contact-heatmap = "squeezemd.analysis.contact_posco.plot_contact_heatmap:main"

# Analysis Prolif
compute-proflif-fingerprints = "squeezemd.analysis.contact_prolif.compute_prolif_fingerprints:main"
analyze-proflif-fingerprints = "squeezemd.analysis.contact_prolif.analyze_prolif_fingerprints:main"

# Analysis Trajectory
analyze-potential-energy = "squeezemd.analysis.trajectory.analyze_potential_energy:main"
explore-trajectory = "squeezemd.analysis.trajectory.explore_trajectory:main"
compute-rmsf = "squeezemd.analysis.trajectory.compute_rmsf:main"
plot-rmsf = "squeezemd.analysis.trajectory.plot_rmsf:main"

# Visualization
#visualize-aligned-structures = "squeezemd.analysis.visualization.align_structures:main"
visualize-interaction-surface = "squeezemd.analysis.visualization.visualize_interaction_surface:main"

# Analysis metadynamics
analyze-collective-vars = "squeezemd.analysis.metadynamics.analyze_collective_vars:main"
analyze-metadynamics-hills = "squeezemd.analysis.metadynamics.analyze_metadynamics_hills:main"


[tool.ty]
# All rules are enabled as "error" by default; no need to specify unless overriding.
# Example override: relax a rule for the entire project (uncomment if needed).
# rules.TY015 = "warn"  # For invalid-argument-type, warn instead of error.

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warni--input ... --output align.psengs
    "F",   # Pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
]

[tool.uv]
package = true

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
squeezemd = ["resources/*.yaml","md/*.py", "Snakefile", "resources/pymol_template.pml", "resources/*.rst"]

[tool.setuptools.data-files]
"bin" = ["scripts/squeeze",
        "scripts/squeeze_test",
        "src/squeezemd/analysis/visualization/visualize_aligned_structures.py"]

