mutations:
      - WT

complexes:
  C1s_dr242:
    receptor: C1s
    ligand: dr_242
    pdb: pdb/C1s_8TYP.pdb
    sdf: ligands/dr_242.sdf


  C1s_dr242_trans:
    receptor: C1s
    ligand: dr_243_translated
    pdb: pdb/C1s_8TYP.pdb
    sdf: ligands/dr_243_translated.sdf

