import sys, os, yaml
import numpy as np
from importlib.resources import files
from helper_functions import config_deep_update, save_yaml, import_yaml


############################
# Config handling          #
############################

# Merge three different config sources
# 1. Import simulation config
configfile: os.path.join('config', 'sim_config.yaml') 

# 2. Import and merge Molecular dynamics config
config_md = import_yaml('config/md_config.yaml')
config.update(config_md)        # Merge simulation and md params together

#  test situation
if 'test' in config:
    print("ATTENTION: This is a testrun")
    test_md_config = files("squeezemd").joinpath("resources/md_test_config.yaml")
    md_test = import_yaml(test_md_config)
    config = config_deep_update(config, md_test)
    save_yaml(config, 'config/md_test_config.yaml')

    md_config = 'config/md_test_config.yaml'
else: # Production run
    print("Production run")
    md_config = 'config/md_config.yaml'

COMPLEXES = list(config.get("complexes").keys())
mutations = config['mutations']
n_frames = config['simulation']['number_frames']

# Seed generation
seed = config.get('seed', 23)
np.random.seed(seed)              # Ensure reproducibility
seeds = np.random.randint(100, 1000, size=config['simulation']['replicates'])
representative_seed = seeds[0] # First seeds is used as representation for surface interaction analysis

mode = config.get('mode', 'protein_protein')

rule protein_protein: # protein-protein interaction analysis
    input:
        'results/alignment/align.pse',
        expand('{mode}/{complex}/{mutation}/{seed}/fingerprint/fingerprint.parquet',complex=COMPLEXES,mutation=mutations,seed=seeds,mode=mode),
        'results/posco/lig_heatmap.svg',
        'results/posco/lig_barplot.svg',
        'results/rmsf/rmsf.svg',
        expand('results/interactionSurface/{complex}.{mutation}.interaction.pdb', complex=COMPLEXES, mutation=mutations),

rule metadynamics:
    input:
        expand('metadynamics/{complex}/{mutation}/{seed}/metadynamics/fes.dat',complex=COMPLEXES, mutation=mutations, seed=seeds),
        expand('metadynamics/{complex}/{mutation}/{seed}/metadynamics/freeenergy.png',complex=COMPLEXES, mutation=mutations, seed=seeds),
        'results/alignment/align.pse',
        expand('metadynamics/{complex}/{mutation}/{seed}/fingerprint/fingerprint.parquet',complex=COMPLEXES,mutation=mutations,seed=seeds),
        'results/posco/lig_heatmap.svg',
        'results/posco/lig_barplot.svg',
        'results/rmsf/rmsf.svg',
        expand('results/interactionSurface/{complex}.{mutation}.interaction.pdb', complex=COMPLEXES, mutation=mutations),

rule protein_molecule:
    input:
        expand('protein_molecule/{complex}/{mutation}/{seed}/MD/energy/potential_energy.parquet', complex=COMPLEXES, mutation=mutations, seed=seeds),    
        'results/posco/posco_interactions.parquet',
        'results/alignment/align.pse',
        'results/rmsf/rmsf.svg',
        #expand('molecule/{complex}/{mutation}/{seed}/aquaduct/aquaduct.pse',complex=COMPLEXES, mutation=mutations, seed=seeds)

# Run a apo protein only
rule protein:
    input:
        expand('protein/{complex}/{mutation}/{seed}/MD/center/trajectory_centered.dcd', complex=COMPLEXES, mutation=mutations, seed=seeds),
        expand('protein/{complex}/{mutation}/{seed}/analysis/RMSF.html', complex=COMPLEXES, mutation=mutations, seed=seeds),
        expand('protein/{complex}/{mutation}/{seed}/aquaduct/aquaduct.pse',complex=COMPLEXES, mutation=mutations, seed=seeds)

rule prep_mutagenesis:
    input:
        md_config,
        'config/sim_config.yaml'
    output:
        '{mode}/{complex}/{mutation}/mutation.pdb'
    params:
        out_dir=directory('{mode}/{complex}/{mutation}'),
        foldX='foldx_20261231',
        pdb=lambda wc: config["complexes"][wc.complex]["pdb"]
    log:
        '{mode}/{complex}/{mutation}/mutation.log'
    shell:
        """
        if [[ {wildcards.mutation} = WT ]]
        then    # No mutagenesis
            cp {params.pdb} {output}
        else    # Mutate
            mutate --mutation {wildcards.mutation} --ligand {params.pdb} --output {wildcards.mode}/{wildcards.complex}/{wildcards.mutation}/mutant_file.txt
            cp {params.pdb} {params.out_dir}/WT.pdb
            {params.foldX} --command=BuildModel --pdb-dir="{params.out_dir}" --pdb=WT.pdb --mutant-file={wildcards.mode}/{wildcards.complex}/{wildcards.mutation}/mutant_file.txt --output-dir="{params.out_dir}" --rotabaseLocation ~/tools/foldX/foldx_Linux/rotabase.txt > {log} || true
            mv {params.out_dir}/WT_1.pdb {output}
        fi
        """

rule md_protein_protein:
    input:   
        md_settings=ancient(md_config),
        pdb='protein_protein/{complex}/{mutation}/mutation.pdb',
    output:
        equilibrated='protein_protein/{complex}/{mutation}/{seed}/MD/structure_equilibrated.pdb',
        topo_cif='protein_protein/{complex}/{mutation}/{seed}/MD/structure_end.cif',
        traj=temp('protein_protein/{complex}/{mutation}/{seed}/MD/trajectory_raw.h5'),
        stats='protein_protein/{complex}/{mutation}/{seed}/MD/mdstats.csv'
    resources: gpu=1
    priority: 3
    shell:
        """
        run-md --pdb {input.pdb} \
                  --equilibrated {output.equilibrated} \
                  --topo_cif {output.topo_cif} \
                  --traj {output.traj} \
                  --md_settings {input.md_settings} \
                  --seed {wildcards.seed} \
                  --stats {output.stats} \
                  --mode protein_protein
        """

rule md_protein_molecule:
    input:   
        md_settings=ancient(md_config),
        pdb='protein_molecule/{complex}/{mutation}/mutation.pdb',
        sdf=lambda wc: config["complexes"][wc.complex]["sdf"]
    output:
        equilibrated='protein_molecule/{complex}/{mutation}/{seed}/MD/structure_equilibrated.pdb',
        topo_cif='protein_molecule/{complex}/{mutation}/{seed}/MD/structure_end.cif',
        traj=temp('protein_molecule/{complex}/{mutation}/{seed}/MD/trajectory_raw.h5'),
        stats='protein_molecule/{complex}/{mutation}/{seed}/MD/mdstats.csv',
    resources: gpu=1
    priority: 3
    shell:
        """
        run-md --pdb {input.pdb} \
                  --equilibrated {output.equilibrated} \
                  --topo_cif {output.topo_cif} \
                  --traj {output.traj} \
                  --md_settings {input.md_settings} \
                  --seed {wildcards.seed} \
                  --stats {output.stats} \
                  --sdf {input.sdf} \
                  --mode protein_molecule
        """

rule md_metadynamics:
    input:   
        md_settings=ancient(md_config),
        pdb='metadynamics/{complex}/{mutation}/mutation.pdb',
    output:
        equilibrated = 'metadynamics/{complex}/{mutation}/{seed}/MD/structure_equilibrated.pdb',
        topo_cif = 'metadynamics/{complex}/{mutation}/{seed}/MD/structure_end.cif',
        traj=temp('metadynamics/{complex}/{mutation}/{seed}/MD/trajectory_raw.h5'),
        stats='metadynamics/{complex}/{mutation}/{seed}/MD/mdstats.csv',
        metadynamics_hill='metadynamics/{complex}/{mutation}/{seed}/metadynamics/metadynamics_hill.txt',
        metadynamics_colvar='metadynamics/{complex}/{mutation}/{seed}/metadynamics/Colvar.dat'
    resources: gpu=1
    priority: 3
    shell:
        """
        run-md --pdb {input.pdb} \
                  --equilibrated {output.equilibrated} \
                  --topo_cif {output.topo_cif} \
                  --traj {output.traj} \
                  --md_settings {input.md_settings} \
                  --seed {wildcards.seed} \
                  --stats {output.stats} \
                  --metadynamics_hill {output.metadynamics_hill} \
                  --metadynamics_colvar {output.metadynamics_colvar} \
                  --mode metadynamics
        """

rule ana_potential_energy:
    input:
        topo='protein_molecule/{complex}/{mutation}/{seed}/MD/structure_equilibrated.pdb',
        traj='protein_molecule/{complex}/{mutation}/{seed}/MD/trajectory_raw.h5',           
        md_config=ancient(md_config),
        sdf=lambda wc: config["complexes"][wc.complex]["sdf"]
    output:
        'protein_molecule/{complex}/{mutation}/{seed}/MD/energy/potential_energy.parquet',
    resources: gpu=1
    priority: 3
    shell:
        """
        analyze-potential-energy --topo {input.topo} \
                                    --traj {input.traj} \
                                    --config {input.md_config} \
                                    --sdf {input.sdf} \
                                    --energy {output}
        """

rule center_trajectory:
    input:
        topo='{mode}/{complex}/{mutation}/{seed}/MD/structure_end.cif',
        traj='{mode}/{complex}/{mutation}/{seed}/MD/trajectory_raw.h5'
    output:
        topo_center='{mode}/{complex}/{mutation}/{seed}/MD/center/structure_end_center_{seed}.pdb',
        traj_center='{mode}/{complex}/{mutation}/{seed}/MD/center/trajectory_centered.dcd',
        traj_center_h5='{mode}/{complex}/{mutation}/{seed}/MD/center/trajectory_centered.h5'
    priority: 3
    shell:
        """
        center-traj --topo {input.topo} \
                             --traj {input.traj} \
                             --traj_center {output.traj_center} \
                             --topo_center {output.topo_center} \
                             --traj_center_h5 {output.traj_center_h5}
        """

rule metadynamics_run:
    input:   
        'metadynamics/{complex}/{mutation}/{seed}/metadynamics/metadynamics_hill.txt'
    output:
        'metadynamics/{complex}/{mutation}/{seed}/metadynamics/fes.dat'
    shell:
        "plumed sum_hills --hills {input} --outfile {output}"

rule metadynamics_ana:
    input:
        fes='metadynamics/{complex}/{mutation}/{seed}/metadynamics/fes.dat',
        colvar='metadynamics/{complex}/{mutation}/{seed}/metadynamics/Colvar.dat',
    output:
        freeenergy='metadynamics/{complex}/{mutation}/{seed}/metadynamics/freeenergy.png',
        colvar_fig='metadynamics/{complex}/{mutation}/{seed}/metadynamics/colvar.png',
    shell:
        """
        analyze-collective-vars --colvar {input.colvar} --colvar_fig {output.colvar_fig} &&
        analyze-metadynamics-hills --fes {input.fes} --freeenergy {output.freeenergy}
        """

# TODO: Path is fragile
rule visualize_structure_alignment:
    input:
        expand('{mode}/{complex}/{mutation}/{seed}/MD/center/structure_end_center_{seed}.pdb',complex=COMPLEXES, mutation=mutations, seed=seeds, mode=mode),
    output:
        'results/alignment/align.pse'
    params: os.path.join(os.environ['CONDA_PREFIX'], 'lib', 'python3.12','site-packages','squeezemd','analysis','visualization','visualize_aligned_structures.py')
    shell:
        "pymol -c {params} --input {input} --output {output}"

rule ana_aquaduct:
    input:
        topo_center = '{mode}/{complex}/{mutation}/{seed}/MD/center/structure_end_center_{seed}.pdb',
        traj_center='{mode}/{complex}/{mutation}/{seed}/MD/center/trajectory_centered.dcd',
        aquaduct_template='config/TEMPLATE_aquaduct.txt',
    output:
        aquaduct='{mode}/{complex}/{mutation}/{seed}/aquaduct/aquaduct.txt',
        aquaduct_folder=directory('{mode}/{complex}/{mutation}/{seed}/aquaduct/'),
        pymol_cmd='{mode}/{complex}/{mutation}/{seed}/aquaduct/6_visualize_results.py',
    params:
        directory('{mode}/{complex}/{mutation}/{seed}')
    conda: "aquaduct"
    shell:
        """
        sed  's|PREFIXINPUT|{params}|g' {input.aquaduct_template} > {output.aquaduct} &&
        sed  -i 's|PREFIXOUT|{output.aquaduct_folder}|g' {output.aquaduct} &&
        valve_run -c {output.aquaduct}
        """

rule ana_aquaduct_pymol:
    input:
        '{mode}/{complex}/{mutation}/{seed}/aquaduct/6_visualize_results.py',
    output:
        '{mode}/{complex}/{mutation}/{seed}/aquaduct/aquaduct.pse',
    params:
        directory('{complex}/{mutation}/{seed}')
    shell:
        "python3 {input} --save-session {output}"

rule ana_trajectory_descriptive:
    input:
        topo='{mode}/{complex}/{mutation}/{seed}/MD/structure_end.cif',
        traj='{mode}/{complex}/{mutation}/{seed}/MD/center/trajectory_centered.dcd',
        stats='{mode}/{complex}/{mutation}/{seed}/MD/mdstats.csv'
    output:
        rmsf= report('{mode}/{complex}/{mutation}/{seed}/analysis/RMSF.html',caption="RMSF.rst",category="RMSF",labels={"Complex": "{complex}", "Mutation": "{mutation}"}),
        rmsd= report('{mode}/{complex}/{mutation}/{seed}/analysis/RMSD.svg',caption="RMSF.rst",category="RMSD",labels={"Complex": "{complex}", "Mutation": "{mutation}"}),
        rmsd_raw= '{mode}/{complex}/{mutation}/{seed}/analysis/RMSD.csv',
        bfactors='{mode}/{complex}/{mutation}/{seed}/analysis/bfactors.pdb',
        stats='{mode}/{complex}/{mutation}/{seed}/analysis/Stats.svg',
    params:
        number_frames = n_frames
    shell:
        """
        explore-trajectory --topo {input.topo} \
                              --traj {input.traj} \
                              --stats {input.stats} \
                              --rmsf {output.rmsf} \
                              --bfactors {output.bfactors} \
                              --rmsd {output.rmsd} \
                              --rmsd_raw {output.rmsd_raw} \
                              --fig_stats {output.stats}
        """

rule ana_rmsf:
    input:
        topo = expand('{mode}/{complex}/{mutation}/{seed}/MD/structure_end.cif',complex=COMPLEXES, mutation=mutations, seed=seeds, mode=mode),
        traj = expand('{mode}/{complex}/{mutation}/{seed}/MD/center/trajectory_centered.dcd',  complex=COMPLEXES, mutation=mutations, seed=seeds, mode=mode), 
    output:
        'results/rmsf/rmsf.parquet'
    shell:
        """
        compute-rmsf --topo {input.topo} \
                        --traj {input.traj} \
                        --output {output}
        """

rule plot_rmsf:
    input:
        'results/rmsf/rmsf.parquet'
    output:
        'results/rmsf/rmsf.svg'
    shell:
        """
        plot-rmsf --input {input} \
                     --output {output}
        """

rule compute_posco_contacts:
    input:
        topo='{mode}/{complex}/{mutation}/{seed}/MD/structure_end.cif',
        traj='{mode}/{complex}/{mutation}/{seed}/MD/center/trajectory_centered.dcd'
    output:
        lig_frame=temp('{mode}/{complex}/{mutation}/{seed}/frames/lig_{i}.pdb'),
        rec_frame=temp('{mode}/{complex}/{mutation}/{seed}/frames/rec_{i}.pdb'),
        posco = '{mode}/{complex}/{mutation}/{seed}/po-sco/{i}.txt'
    params:
        sequence='{mode}/{complex}/{mutation}/{seed}/frames/sequence.parquet'
    shell:
        """
        extract-contact-frames  --topo {input.topo} \
                                   --traj {input.traj} \
                                   --frame {wildcards.i} \
                                   --lig_frame {output.lig_frame} \
                                   --rec_frame {output.rec_frame} \
                                   --sequence {params.sequence} && \
        po-sco {output.rec_frame} {output.lig_frame} -b  > {output.posco}
        """

rule ana_contacts_concat:
    input:
        posco = expand('{mode}/{complex}/{mutation}/{seed}/po-sco/{i}.txt', i=range(n_frames), complex=COMPLEXES, mutation=mutations, seed=seeds, mode= mode),
    output:
        'results/posco/posco_interactions.parquet'
    shell:
        "transform-contact-data --input {input.posco} --output {output}"

rule plot_contacts_heatmap:
    input:
        data='results/posco/posco_interactions.parquet'
    output:
        lig_heatmap='results/posco/lig_heatmap.svg',
        rec_heatmap='results/posco/rec_heatmap.svg',
    shell:
        "plot-contact-heatmap --input {input.data} --ligand_interaction {output.lig_heatmap} --receptor_interaction {output.rec_heatmap}"


rule plot_contacts_barplot:             # TODO: does not work for mutations of differnt complexes yet!!
    input:
        'results/posco/posco_interactions.parquet',  
    output:
        lig_barplot='results/posco/lig_barplot.svg',
        rec_barplot='results/posco/rec_barplot.svg',
    shell:
        """
        plot-contact-barplot --input {input} \
                                --ligand_interaction {output.lig_barplot} \
                                --receptor_interaction {output.rec_barplot}
        """

rule ana_prolif_contacts:
    input:
        topo='{mode}/{complex}/{mutation}/{seed}/MD/structure_end.cif',
        traj='{mode}/{complex}/{mutation}/{seed}/MD/center/trajectory_centered.dcd',
    output:
        report('{mode}/{complex}/{mutation}/{seed}/fingerprint/fingerprint.parquet', labels=({"Name": "Interaction Analysis Prolif", "Type": "List"}),caption="RMSF.rst",category="Interaction Fingerprint")
    params:
        number_frames = n_frames
    threads: 4
    shell:
        """
        compute-proflif-fingerprints --topo {input.topo} \
                                       --traj  {input.traj} \
                                       --output {output} \
                                       --n_frames {params.number_frames} \
                                       --threads {threads} \
                                       --complex {wildcards.complex} \
                                       --mutation {wildcards.mutation} \
                                       --seed {wildcards.seed}
        """

rule plot_prolif_contacts:
    input:
        fingerprints=expand('{mode}/{complex}/{mutation}/{seed}/fingerprint/fingerprint.parquet', complex=COMPLEXES, mutation=mutations, seed=seeds, mode=mode),
    output:
        interactions = report('results/fingerprints/interactions.parquet',labels=({"Name": "Interaction Analysis Prolif", "Type": "List"}),caption="RMSF.rst",category="Interaction Fingerprint"),
        figure = report('results/fingerprints/fingerprints.html',labels=({"Name": "Interaction Analysis Prolif", "Type": "Plot"}),caption="RMSF.rst",category="Interaction Fingerprint"),
    params:
        n_frames = n_frames
    shell:
        """
        analyze-proflif-fingerprints --fingerprints {input.fingerprints} \
                                        --interactions {output.interactions} \
                                        --n_frames {params.n_frames} \
                                        --figure {output.figure}
        """

rule visualize_interaction_surface:
    input:
        final_frame = f'{mode}/{{complex}}/{{mutation}}/{representative_seed}/MD/center/structure_end_center_{representative_seed}.pdb',
        interactions= 'results/posco/posco_interactions.parquet',
    output:
        bfactor_pdbs = 'results/interactionSurface/{complex}.{mutation}.interaction.pdb',
        pymol_cmd = 'results/interactionSurface/{complex}.{mutation}.pml',
        pymol = report('results/interactionSurface/{complex}.{mutation}.final.pse',caption="RMSF.rst",category="PyMol",labels=({"Complex": "{complex}", "Mutation": "{mutation}", "Type": "PyMol"})),
        surface= report('results/interactionSurface/{complex}.{mutation}.png',caption="RMSF.rst",category="PyMol", labels=({"Complex": "{complex}", "Mutation": "{mutation}", "Type": "Image"}))
    params:
        representative_seed = seeds[0],
    shell:
        """
        visualize-interaction-surface --interactions {input.interactions} \
                                         --seed {params.representative_seed} \
                                         --mutation {wildcards.mutation} \
                                         --complex {wildcards.complex}
        pymol -cQ {output.pymol_cmd}
        """

onsuccess:
    print(f"Workflow finished without errors. Report for the mode {mode} will be generated")
    shell(f"squeeze {mode} --report report.html")
    print("Synchronize data to caracara")
    shell("""rsync -auvz "$(pwd)" ~/caracara/Squeeze""")
