mutations:
      - WT

complexes:
  Pepsin_Acetamide_cocryst:
    receptor: pepsin
    ligand: acetamide_cocryst
    pdb: pdb/7IFH_rec.amber.pdb
    sdf: ligands/A1CGO_Acetamide.sdf

  Pepsin_Acetamide_p1:
    receptor: pepsin
    ligand: acetamide_p1
    pdb: pdb/7IFH_rec.amber.pdb
    sdf: ligands/A1CGO_p1.sdf

  Pepsin_Acetamide_p2:
    receptor: pepsin
    ligand: acetamide_p2
    pdb: pdb/7IFH_rec.amber.pdb
    sdf: ligands/A1CGO_p2.sdf

  Pepsin_Acetamide_p3:
    receptor: pepsin
    ligand: acetamide_p3
    pdb: pdb/7IFH_rec.amber.pdb
    sdf: ligands/A1CGO_p3.sdf

  Pepsin_Acetamide_p4:
    receptor: pepsin
    ligand: acetamide_p4
    pdb: pdb/7IFH_rec.amber.pdb
    sdf: ligands/A1CGO_p4.sdf

  Pepsin_Acetamide_p5:
    receptor: pepsin
    ligand: acetamide_p5
    pdb: pdb/7IFH_rec.amber.pdb
    sdf: ligands/A1CGO_p5.sdf
