# This environment install everything required to run squeezeMD
# posco and foldX is installed via the script install_bins_linux.sh

# How to install via conda:
# conda env create -f environment.yml

name: squeeze

channels:
  - conda-forge
  - bioconda                # for snakemake

dependencies:
  - python
  - openmm                  # MD engine
  - openmmforcefields       
  - openff-toolkit          # small molecule forcefield
  - snakemake-minimal       # Automatic workflow engine
  - prolif                  # Interaction fingerprint
  - pandas                  # Data science
  - pyarrow
  - mdtraj                  # For centering protein in water box
  - pymol-open-source       # pymol for interaction surface
  - cudatoolkit             # Cudatoolkit 11.8 works with nvidia driver 535. > 13 for newest driver (Sept 25)
  - seaborn                 # visualisation
  - openmm-plumed           # For metadynamics
  - plotly                  # For trajectory analysis (will be depracted soon)
  - pip
  - pip:
        - json2html         # Html report
        - squeezemd         # The published squeezemd code
        - h5py>=2.10


