#!/usr/bin/env bash


# SqueezeMD specific wrapper around snakemake. Allows to execute squeezeMD in every folder
# without defining the location of the squeezeMD Snakefile required for the pipeline


if [ "$1" = "continue" ]; then
    echo "Continue with squeeze MD"
    ./execute.sh

else
    # use PPi and molecule as alias
    mode="$1"

    if [ "$mode" == "PPi" ]; then
        mode="protein_protein"
    fi

    if [ "$mode" == "molecule" ]; then
        mode="protein_molecule"
    fi

    # replace $1 in "$@" with the mapped value
    shift
    set -- "$mode" "$@"

    # Execute snakemake with all provided arguments
    # Find Snakefile from active environment
    CONDA_BASE_PATH=$CONDA_PREFIX
    echo $CONDA_BASE_PATH

    SNAKEFILE=$(python3 -c 'from importlib.resources import files; print(files("squeezemd").joinpath("Snakefile"))')
    snakemake_cmd="snakemake --use-conda -s "$SNAKEFILE" "$@" --config mode="$mode" test=True"

    # save command
    echo -e "#!/bin/bash\n$snakemake_cmd" > execute.sh

    # execute command
    $snakemake_cmd  
fi
