#!/usr/bin/env bash


# SqueezeMD specific wrapper around snakemake. Allows to execute squeezeMD in every folder
# without defining the location of the squeezeMD Snakefile required for the pipeline

# Check whether the package requires an upgrade
if [ "$1" == "upgrade" ]; then
    # Execute the bash script "upgrade_package.sh" to install the current python package
    # only works for Linux notebook
    upgrade_package.sh

elif [ "$1" = "continue" ]; then
    echo "Continue with squeeze MD"
    ./execute.sh

else
    # Read mode from sim_config.yaml
    mode=$(python3 -c "import yaml; cfg=yaml.safe_load(open('config/sim_config.yaml')); print(cfg['mode'])")
    gp=$(python3 -c "import yaml; cfg=yaml.safe_load(open('config/sim_config.yaml')); print(cfg['gpu'])")
    cpu=$(python3 -c "import yaml; cfg=yaml.safe_load(open('config/sim_config.yaml')); print(cfg['cpu'])")

    # Execute snakemake with all provided arguments
    # Find Snakefile from active environment
    CONDA_BASE_PATH=$CONDA_PREFIX
    echo $CONDA_BASE_PATH

    SNAKEFILE=$(python3 -c 'from importlib.resources import files; print(files("squeezemd").joinpath("Snakefile"))')
    snakemake_cmd="snakemake --use-conda -s $SNAKEFILE $mode --resources gpu=$gp --cores $cpu $@"

    echo $snakemake_cmd

    # save command
    echo -e "#!/bin/bash\n$snakemake_cmd" > execute.sh

    # execute command
    $snakemake_cmd  
fi
