#!/usr/bin/env bash


# SqueezeMD specific wrapper around snakemake. Allows to execute squeezeMD in every folder
# without defining the location of the squeezeMD Snakefile required for the pipeline

# Check whether the package requires an upgrade
if [ "$1" == "upgrade" ]; then
    # Execute the bash script "upgrade_package.sh" to install the current python package
    # only works for Linux notebook
    upgrade_package.sh

elif [ "$1" = "continue" ]; then
    echo "Continue with squeeze MD"
    ./execute.sh
    
else
    # use PPi and molecule as alias
    mode="$1"

    if [ "$mode" == "PPi" ]; then
        mode="protein_protein"
    fi

    if [ "$mode" == "molecule" ]; then
        mode="protein_molecule"
    fi

    # replace $1 in "$@" with the mapped value
    shift
    set -- "$mode" "$@"

    # Execute snakemake with all provided arguments
    # Find Snakefile from active environment
    CONDA_BASE_PATH=$CONDA_PREFIX
    echo $CONDA_BASE_PATH

    # /home/peter/miniconda3/envs/squeeze/lib/python3.13/site-packages/squeezemd/Snakefile
    snakemake_cmd="snakemake --use-conda -s "$CONDA_BASE_PATH/lib/python3.13/site-packages/squeezemd/Snakefile" "$@" --config mode="$mode""

    # save command
    echo -e "#!/bin/bash\n$snakemake_cmd" > execute.sh

    # execute command
    $snakemake_cmd  
fi
