import sys
import numpy as np
import pandas as pd
import yaml
from os import path
from Helper import save_yaml

# ======================
# Configuration Handling
# ======================

# Import the simulation and Molecular dynamics parameters
configfile: path.join('config', 'sim_config.yml') 
with open(path.join('config', 'md_config.yml')) as f:
    config_md = yaml.safe_load(f)
# merge both configs together
config.update(config_md)

COMPLEXES = list(config.get("complexes").keys())
mutations = config['mutations']
n_frames = config['simulation']['number_frames']

# ==================================
# Random Seed Generation for Replicates
# ==================================
seed = config.get("seed", 23)
np.random.seed(seed)  # Ensure reproducibility
seeds = np.random.randint(100, 1000, size=config['simulation']['replicates'])
representative_seed = seeds[0] # First seeds is used as representation for surface interaction analysis

# Run a protein-protein interaction analysis
rule PPi:
    input:
        'results/alignment/align.pse',
        'results/metaReport.html',
        expand('{complex}/{mutation}/{seed}/fingerprint/fingerprint.parquet',complex=COMPLEXES,mutation=mutations,seed=seeds),
        'results/posco/lig_heatmap.svg',
        'results/posco/lig_barplot.svg',
        'results/rmsf/rmsf.svg',
        expand('results/interactionSurface/{complex}.{mutation}.interaction.pdb', complex=COMPLEXES, mutation=mutations),

rule PPi_metadynamics:
    input:
        expand('{complex}/{mutation}/{seed}/metadynamics/fes.dat',complex=COMPLEXES, mutation=mutations, seed=seeds),
        expand('{complex}/{mutation}/{seed}/metadynamics/freeenergy.png',complex=COMPLEXES, mutation=mutations, seed=seeds),
        'results/alignment/align.pse',
        'results/metaReport.html',
        expand('{complex}/{mutation}/{seed}/fingerprint/fingerprint.parquet',complex=COMPLEXES,mutation=mutations,seed=seeds),
        'results/posco/lig_heatmap.svg',
        'results/posco/lig_barplot.svg',
        'results/rmsf/rmsf.svg',
        expand('results/interactionSurface/{complex}.{mutation}.interaction.pdb', complex=COMPLEXES, mutation=mutations),


# run a small molecule protein interaction analysis
rule molecule:
    input:
        'results/metaReport.html',
        expand('{complex}/{mutation}/{seed}/frames/lig_{i}.pdb', i=range(n_frames), complex=COMPLEXES, mutation=mutations, seed=seeds),
        expand('{complex}/{mutation}/{seed}/frames/rec_{i}.pdb', i=range(n_frames), complex=COMPLEXES, mutation=mutations, seed=seeds),
        expand('{complex}/{mutation}/{seed}/po-sco/{i}.txt', i=range(n_frames), complex=COMPLEXES, mutation=mutations, seed=seeds),
        'results/posco/posco_interactions.parquet',
        'results/alignment/align.pse'
        #expand('{complex}/{mutation}/{seed}/aquaduct/aquaduct.pse',complex=COMPLEXES, mutation=mutations, seed=seeds)

# Run a apo protein only
rule protein:
    input:
        expand('{complex}/{mutation}/{seed}/MD/traj_center.dcd', complex=COMPLEXES, mutation=mutations, seed=seeds),
        expand('{complex}/{mutation}/{seed}/analysis/RMSF.html', complex=COMPLEXES, mutation=mutations, seed=seeds),
        expand('{complex}/{mutation}/{seed}/aquaduct/aquaduct.pse',complex=COMPLEXES, mutation=mutations, seed=seeds)

rule metaReport:
    input:
        md_config='config/md_config.yml',
        sim_config='config/sim_config.yml'
    output:
        report('results/metaReport.html',caption="RMSF.rst",category="Meta")
    shell:
        """
        metaReport.py  --param {input.md_config} \
                       --sims {input.sim_config} \
                       --output {output}
        """

rule Mutagensis:
    input:
        'config/md_config.yml',
        'config/sim_config.yml'
    output:
        '{complex}/{mutation}/mutation.pdb'
    params:
        out_dir=directory('{complex}/{mutation}'),
        pdb= lambda wildcards: config['complexes'][wildcards.complex]['pdb'],
        foldX='foldx_20251231'              # Needs to be updated every year
    log:
        '{complex}/{mutation}/mutation.log'
    shell:
        """
        if [[ {wildcards.mutation} = WT ]]
        then    # No mutagenisis
            cp {params.pdb} {output}
        else    # Mutate
            1_mutation.py --mutation {wildcards.mutation} --ligand {params.pdb} --output {wildcards.complex}/{wildcards.mutation}/mutant_file.txt
            cp {params.pdb} {params.out_dir}/WT.pdb
            {params.foldX} --command=BuildModel --pdb-dir="{params.out_dir}" --pdb=WT.pdb --mutant-file={wildcards.complex}/{wildcards.mutation}/mutant_file.txt --output-dir="{params.out_dir}" --rotabaseLocation ~/tools/foldx/rotabase.txt > {log} || true
            mv {params.out_dir}/WT_1.pdb {output}
        fi
        """

rule MD_PPi:
    input:   
        md_settings=ancient('config/md_config.yml'),
        pdb='{complex}/{mutation}/mutation.pdb',
    output:
        equilibrated = '{complex}/{mutation}/{seed}/MD/equilibrated.pdb',
        topo_cif = '{complex}/{mutation}/{seed}/MD/frame_end.cif',
        traj=temp('{complex}/{mutation}/{seed}/MD/trajectory.h5'),
        stats='{complex}/{mutation}/{seed}/MD/MDStats.csv'
    resources: gpu=1
    priority: 3
    shell:
        """
        2_MD.py --pdb {input.pdb} \
                --equilibrated {output.equilibrated} \
                --topo_cif {output.topo_cif} \
                --traj {output.traj} \
                --md_settings {input.md_settings} \
                --seed {wildcards.seed} \
                --stats {output.stats}
        """

rule MD_molecule:
    input:   
        md_settings=ancient('config/md_config.yml'),
        pdb='{complex}/{mutation}/mutation.pdb',
    output:
        equilibrated = '{complex}/{mutation}/{seed}/MD/equilibrated.pdb',
        topo_cif = '{complex}/{mutation}/{seed}/MD/frame_end.cif',
        traj=temp('{complex}/{mutation}/{seed}/MD/trajectory.h5'),
        stats='{complex}/{mutation}/{seed}/MD/MDStats.csv',
        #sdf=lambda wildcards: config['complexes'][wildcards.complex]['pdb'], # This will terribly fail
    resources: gpu=1
    priority: 3
    shell:
        """
        2_MD.py --pdb {input.pdb} \
                --equilibrated {output.equilibrated} \
                --topo_cif {output.topo_cif} \
                --traj {output.traj} \
                --md_settings {input.md_settings} \
                --seed {wildcards.seed} \
                --stats {output.stats} \
                --sdf {output.sdf}
        """

rule MD_metadynamics:
    input:   
        md_settings=ancient('config/md_config.yml'),
        pdb='{complex}/{mutation}/mutation.pdb',
    output:
        equilibrated = '{complex}/{mutation}/{seed}/MD/equilibrated.pdb',
        topo_cif = '{complex}/{mutation}/{seed}/MD/frame_end.cif',
        traj=temp('{complex}/{mutation}/{seed}/MD/trajectory.h5'),
        stats='{complex}/{mutation}/{seed}/MD/MDStats.csv',
        metadynamics_hill='{complex}/{mutation}/{seed}/metadynamics/metadynamics_hill.txt',
        metadynamics_colvar='{complex}/{mutation}/{seed}/metadynamics/Colvar.dat'
    resources: gpu=1
    priority: 3
    shell:
        """
        2_MD.py --pdb {input.pdb} \
                --equilibrated {output.equilibrated} \
                --topo_cif {output.topo_cif} \
                --traj {output.traj} \
                --md_settings {input.md_settings} \
                --seed {wildcards.seed} \
                --stats {output.stats} \
                --metadynamics_hill {output.metadynamics_hill} \
                --metadynamics_colvar {output.metadynamics_colvar}
        """

ruleorder: MD_PPi > MD_molecule > MD_metadynamics


rule metadynamics:
    input:   
        '{complex}/{mutation}/{seed}/metadynamics/metadynamics_hill.txt'
    output:
        '{complex}/{mutation}/{seed}/metadynamics/fes.dat'
    shell:
        """
        plumed sum_hills --hills {input} --outfile {output}
        """

rule metadynamics_ana:
    input:
        fes='{complex}/{mutation}/{seed}/metadynamics/fes.dat',
        colvar='{complex}/{mutation}/{seed}/metadynamics/Colvar.dat',
    output:
        freeenergy='{complex}/{mutation}/{seed}/metadynamics/freeenergy.png',
        colvar_fig='{complex}/{mutation}/{seed}/metadynamics/colvar.png',
    shell:
        """
        14.1_Metadynamics_Colvar_ana.py --colvar {input.colvar} --colvar_fig {output.colvar_fig} &&
        14.2_Metadynamics_Hills_ana.py --fes {input.fes} --freeenergy {output.freeenergy}
        """

rule centerMDTraj:
    input:
        topo='{complex}/{mutation}/{seed}/MD/frame_end.cif',
        traj='{complex}/{mutation}/{seed}/MD/trajectory.h5',
    output:
        topo_center = '{complex}/{mutation}/{seed}/MD/topo_center_{seed}.pdb',
        traj_center='{complex}/{mutation}/{seed}/MD/traj_center.dcd',
    priority:
        3
    shell:
        """
        4_centerMDTraj.py   --topo {input.topo} \
                            --traj {input.traj} \
                            --traj_center {output.traj_center} \
                            --topo_center {output.topo_center}
        """

rule align:
    input:
        expand('{complex}/{mutation}/{seed}/MD/topo_center_{seed}.pdb',complex=COMPLEXES, mutation=mutations, seed=seeds),
    output:
        'results/alignment/align.pse'
    params: os.path.join(os.environ['CONDA_PREFIX'], 'bin', '6_Align.py')
    shell:
        "pymol -c {params} --input {input} --output {output}"

rule aquaduct:
    input:
        topo_center = '{complex}/{mutation}/{seed}/MD/topo_center_{seed}.pdb',
        traj_center='{complex}/{mutation}/{seed}/MD/traj_center.dcd',
        aquaduct_template='config/TEMPLATE_aquaduct.txt',
    output:
        aquaduct='{complex}/{mutation}/{seed}/aquaduct/aquaduct.txt',
        aquaduct_folder=directory('{complex}/{mutation}/{seed}/aquaduct/'),
        pymol_cmd='{complex}/{mutation}/{seed}/aquaduct/6_visualize_results.py',
    priority:
        10
    params:
        directory('{complex}/{mutation}/{seed}')
    conda:
        "aquaduct"
    shell:
        """
        sed  's|PREFIXINPUT|{params}|g' {input.aquaduct_template} > {output.aquaduct} &&
        sed  -i 's|PREFIXOUT|{output.aquaduct_folder}|g' {output.aquaduct} &&
        valve_run -c {output.aquaduct}
        """

rule aquaductPymol:
    input:
        '{complex}/{mutation}/{seed}/aquaduct/6_visualize_results.py',
    output:
        '{complex}/{mutation}/{seed}/aquaduct/aquaduct.pse',
    priority:
        10
    params:
        directory('{complex}/{mutation}/{seed}')
    shell:
        """
        python3 {input} --save-session {output}
        """

rule DescriptiveTrajAnalysis:
    input:
        topo='{complex}/{mutation}/{seed}/MD/frame_end.cif',
        traj='{complex}/{mutation}/{seed}/MD/traj_center.dcd',
        stats='{complex}/{mutation}/{seed}/MD/MDStats.csv'
    output:
        rmsf= report('{complex}/{mutation}/{seed}/analysis/RMSF.html',caption="RMSF.rst",category="RMSF",labels={"Complex": "{complex}", "Mutation": "{mutation}"}),
        rmsd= report('{complex}/{mutation}/{seed}/analysis/RMSD.svg',caption="RMSF.rst",category="RMSD",labels={"Complex": "{complex}", "Mutation": "{mutation}"}),
        rmsd_raw= '{complex}/{mutation}/{seed}/analysis/RMSD.csv',
        bfactors='{complex}/{mutation}/{seed}/analysis/bfactors.pdb',
        stats='{complex}/{mutation}/{seed}/analysis/Stats.svg',
    params:
        number_frames = n_frames
    shell:
        """
        3.1_ExplorativeTrajectoryAnalysis.py --topo {input.topo} \
                                                   --traj {input.traj} \
                                                   --stats {input.stats} \
                                                   --rmsf {output.rmsf} \
                                                   --bfactors {output.bfactors} \
                                                   --rmsd {output.rmsd} \
                                                   --rmsd_raw {output.rmsd_raw} \
                                                   --fig_stats {output.stats}
        """

rule calculateRMSF:
    input:
        topo = expand('{complex}/{mutation}/{seed}/MD/frame_end.cif',complex=COMPLEXES, mutation=mutations, seed=seeds),
        traj = expand('{complex}/{mutation}/{seed}/MD/traj_center.dcd',  complex=COMPLEXES, mutation=mutations, seed=seeds), 
    output:
        'results/rmsf/rmsf.parquet'
    shell:
        """
        3.2_Compute_RMSF.py --topo {input.topo} \
                            --traj {input.traj} \
                            --output {output}
        """

rule visualiseRMSF:
    input:
        'results/rmsf/rmsf.parquet'
    output:
        'results/rmsf/rmsf.svg'
    shell:
        """
        3.3_Visualize_RMSF.py --input {input} \
                              --output {output}
        """


rule ExtractithFrameFromTrajectory:
    input:
        topo='{complex}/{mutation}/{seed}/MD/frame_end.cif',
        traj='{complex}/{mutation}/{seed}/MD/traj_center.dcd'
    output:
        lig_frame='{complex}/{mutation}/{seed}/frames/lig_{i}.pdb',
        rec_frame='{complex}/{mutation}/{seed}/frames/rec_{i}.pdb'
    params:
        sequence='{complex}/{mutation}/{seed}/frames/sequence.parquet'
    threads: 1
    shell:
        """
        5.1_Posco_ExtractLastFrames.py  --topo {input.topo} \
                                        --traj {input.traj} \
                                        --frame {wildcards.i} \
                                        --lig_frame {output.lig_frame} \
                                        --rec_frame {output.rec_frame} \
                                        --sequence {params.sequence}
        """
rule posco:
    input:
        lig_frames='{complex}/{mutation}/{seed}/frames/lig_{i}.pdb',
        rec_frames='{complex}/{mutation}/{seed}/frames/rec_{i}.pdb',
    output:
        '{complex}/{mutation}/{seed}/po-sco/{i}.txt'
    threads: 1
    shell:
        """
        po-sco {input.rec_frames} {input.lig_frames} -b  > {output}
        """

# PosCo
rule concatPosco:
    input:
        posco = expand('{complex}/{mutation}/{seed}/po-sco/{i}.txt', i=range(n_frames), complex=COMPLEXES, mutation=mutations, seed=seeds),
    output:
        'results/posco/posco_interactions.parquet'
    shell:
        """5.2_Posco_TransformDF.py --input {input.posco} --output {output}"""


# PosCo
rule PoScoHeatMap:
    input:
        data='results/posco/posco_interactions.parquet'
    output:
        lig_heatmap='results/posco/lig_heatmap.svg',
        rec_heatmap='results/posco/rec_heatmap.svg',
    shell:
        """
        5.4_Posco_Heatmap.py --input {input.data} --ligand_interaction {output.lig_heatmap} --receptor_interaction {output.rec_heatmap}
        """

# PosCo
# TODO: does not work for mutations of differnt complexes yet!!
rule PoScoBarplot:
    input:
        'results/posco/posco_interactions.parquet',  
    output:
        lig_barplot='results/posco/lig_barplot.svg',
        rec_barplot='results/posco/rec_barplot.svg',
    shell:
        """
        5.5_Posco_Barplot.py --input {input} \
                             --ligand_interaction {output.lig_barplot} \
                             --receptor_interaction {output.rec_barplot}
        """

rule interactionFingerprint:
    input:
        topo='{complex}/{mutation}/{seed}/MD/frame_end.cif',
        traj='{complex}/{mutation}/{seed}/MD/traj_center.dcd',
    output:
        report('{complex}/{mutation}/{seed}/fingerprint/fingerprint.parquet', labels=({"Name": "Interaction Analysis Prolif", "Type": "List"}),caption="RMSF.rst",category="Interaction Fingerprint")
    params:
        number_frames = n_frames
    threads: 4
    shell:
        """
        7_interactionFingerprint.py --topo {input.topo} \
                                    --traj  {input.traj} \
                                    --output {output} \
                                    --n_frames {params.number_frames} \
                                    --threads {threads} \
                                    --complex {wildcards.complex} \
                                    --mutation {wildcards.mutation} \
                                    --seed {wildcards.seed}
        """

rule GlobalFingerprintAnalysis:
    input:
        fingerprints=expand('{complex}/{mutation}/{seed}/fingerprint/fingerprint.parquet', complex=COMPLEXES, mutation=mutations, seed=seeds),
    output:
        interactions = report('results/fingerprints/interactions.parquet',labels=({"Name": "Interaction Analysis Prolif", "Type": "List"}),caption="RMSF.rst",category="Interaction Fingerprint"),
        figure = report('results/fingerprints/fingerprints.html',labels=({"Name": "Interaction Analysis Prolif", "Type": "Plot"}),caption="RMSF.rst",category="Interaction Fingerprint"),
    params:
        n_frames = n_frames
    shell:
        """
        8_GlobalFinterprintAnalysis.py  --fingerprints {input.fingerprints} \
                                        --interactions {output.interactions} \
                                        --n_frames {params.n_frames} \
                                        --figure {output.figure}
        """

rule InteractionSurface:
    input:
        final_frame = f'{{complex}}/{{mutation}}/{representative_seed}/MD/topo_center_{representative_seed}.pdb',
        interactions= 'results/posco/posco_interactions.parquet',
    output:
        bfactor_pdbs = 'results/interactionSurface/{complex}.{mutation}.interaction.pdb',
        pymol_cmd = 'results/interactionSurface/{complex}.{mutation}.pml',
        pymol = report('results/interactionSurface/{complex}.{mutation}.final.pse',caption="RMSF.rst",category="PyMol",labels=({"Complex": "{complex}", "Mutation": "{mutation}", "Type": "PyMol"})),
        surface= report('results/interactionSurface/{complex}.{mutation}.png',caption="RMSF.rst",category="PyMol", labels=({"Complex": "{complex}", "Mutation": "{mutation}", "Type": "Image"}))
    params:
        representative_seed = seeds[0],
    shell:
        """
        10_InteractionSurface.py --interactions {input.interactions} \
                                 --seed {params.representative_seed} \
                                 --mutation {wildcards.mutation} \
                                 --complex {wildcards.complex}
        pymol -cQ {output.pymol_cmd}
        """

onsuccess:
    # If only single protein has been analyzed
    if 'protein' in sys.argv:
        print("Workflow finished, no error. Report for single protein will be generated")
        shell("squeeze protein --report report.html")

    elif 'molecule' in sys.argv:
        print("Workflow finished, no error. Report for small molecule will be generated")
        shell("squeeze molecule --report report.html")
    else:
        print("Workflow finished, no error. Report for protein-protein Interaction will be generated")
        shell("squeeze PPi --report report.html")
