#!/bin/bash

# SqueezeMD specific wrapper around snakemake. Allows to execute squeezeMD in every folder
# without defining the location of the squeezeMD Snakefile required for the pipeline

# Check whether the package requires an upgrade
if [ "$1" == "upgrade" ]; then
    # Execute the bash script "upgrade_package.sh" to install the current python package
    # only works for Linux notebook
    upgrade_package.sh
else
    # use PPi and molecule as alias
    mode="$1"

    if [ "$mode" == "PPi" ]; then
        mode="protein_protein"
    fi

    if [ "$mode" == "molecule" ]; then
        mode="protein_molecule"
    fi

    # replace $1 in "$@" with the mapped value
    shift
    set -- "$mode" "$@"

    # Execute snakemake with all provided arguments
    # Find Snakefile from active environment
    CONDA_BASE_PATH=$CONDA_PREFIX
    snakemake --use-conda -s "$CONDA_BASE_PATH/bin/Snakefile" "$@"
fi
